name = "bg-remover-worker"
main = "worker.js"
compatibility_date = "2024-01-01"

# D1 Database Binding
[[d1_databases]]
binding = "DB"
database_name = "bg-remover-db"
database_id = "7300c68b-20cb-4fb2-b058-904261826692"
